#!/bin/bash

#tc -s -d qdisc ls
#watch -n 1 tc -s qdisc show dev eth0

tc qdisc del dev eth0 root
tc qdisc add dev eth0 root handle 1: prio bands 8

tc qdisc add dev eth0 parent 1:1 handle 10: tbf rate 10000kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:2 handle 20: tbf rate 10kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:3 handle 30: tbf rate 20kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:4 handle 40: tbf rate 30kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:5 handle 50: tbf rate 40kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:6 handle 60: tbf rate 50kbit latency 30ms burst 1540
tc qdisc add dev eth0 parent 1:7 handle 70: tbf rate 60kbit latency 50ms burst 1540
tc qdisc add dev eth0 parent 1:8 handle 80: tbf rate 80kbit latency 50ms burst 1540


tc qdisc del dev eth1 root
tc qdisc add dev eth1 root handle 1: prio bands 8

tc qdisc add dev eth1 parent 1:1 handle 10: tbf rate 10000kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:2 handle 20: tbf rate 10kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:3 handle 30: tbf rate 20kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:4 handle 40: tbf rate 30kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:5 handle 50: tbf rate 40kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:6 handle 60: tbf rate 50kbit latency 30ms burst 1540
tc qdisc add dev eth1 parent 1:7 handle 70: tbf rate 60kbit latency 50ms burst 1540
tc qdisc add dev eth1 parent 1:8 handle 80: tbf rate 80kbit latency 50ms burst 1540


ip route del 192.168.2.32/27 dev eth2
ip route add 192.168.2.32/27 dev eth2 realm 2

ip route del 192.168.2.64/27 dev eth2
ip route add 192.168.2.64/27 dev eth2 realm 3

ip route del 192.168.2.96/27 dev eth2
ip route add 192.168.2.96/27 dev eth2 realm 4

ip route del 192.168.2.128/27 dev eth2
ip route add 192.168.2.128/27 dev eth2 realm 5

ip route del 192.168.2.160/27 dev eth2
ip route add 192.168.2.160/27 dev eth2 realm 6

ip route del 192.168.2.192/27 dev eth2
ip route add 192.168.2.192/27 dev eth2 realm 7

ip route del 192.168.2.224/27 dev eth2
ip route add 192.168.2.224/27 dev eth2 realm 8


tc filter add dev eth0 parent 1: protocol ip prio 1 route from 2 flowid 1:2
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 3 flowid 1:3
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 4 flowid 1:4
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 5 flowid 1:5
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 6 flowid 1:6
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 7 flowid 1:7
tc filter add dev eth0 parent 1: protocol ip prio 1 route from 8 flowid 1:8


tc filter add dev eth1 parent 1: protocol ip prio 1 route from 2 flowid 1:2
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 3 flowid 1:3
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 4 flowid 1:4
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 5 flowid 1:5
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 6 flowid 1:6
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 7 flowid 1:7
tc filter add dev eth1 parent 1: protocol ip prio 1 route from 8 flowid 1:8

